version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 183631337776.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t webserver .
      - docker tag webserver:latest 183631337776.dkr.ecr.us-east-1.amazonaws.com/webserver:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 183631337776.dkr.ecr.us-east-1.amazonaws.com/webserver:latest
      - echo '[{"name":"webserver","imageUri":"183631337777.dkr.ecr.us-east-1.amazonaws.com/webserver:latest"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
